version: '2'
services:


  #Database
  db: 
    image: postgres
    environment:
      - POSTGRES_USER=crm #Automaticamente crea una DB con ese mismo nombre y de la que crm es superuser.
      - POSTGRES_PASSWORD=xxxx
    expose:
      - "5432"
    networks:
      LAN4: 
        ipv4_address: 10.1.4.31

  #Servers
  s1:
    build: sx/
    image: crm
    privileged: true
    command: npm run-script supervisor
    environment: 
      - DATABASE_URL=postgres://crm:xxxx@10.1.4.31:5432/crm
    networks:
      LAN3:
        ipv4_address: 10.1.3.11
      LAN4:
        ipv4_address: 10.1.4.11

  s2:
    build: sx/
    image: crm
    command: npm run-script supervisor
    privileged: true
    environment: 
     - DATABASE_URL=postgres://crm:xxxx@10.1.4.31:5432/crm
    networks:
      LAN3:
        ipv4_address: 10.1.3.12
      LAN4:
        ipv4_address: 10.1.4.12

  s3:
    build: sx/
    image: crm
    privileged: true
    command: npm run-script supervisor
    environment: 
     - DATABASE_URL=postgres://crm:xxxx@10.1.4.31:5432/crm
    networks:
      LAN3:
        ipv4_address: 10.1.3.13
      LAN4:
        ipv4_address: 10.1.4.13
  #LB
  lb: 
    build: lb/
    image: lb
    privileged: true
    ports:
      - "80:80"
      - "8001:8001"
    networks:
      LAN2:
        ipv4_address: 10.1.2.2
      LAN3:
        ipv4_address: 10.1.3.2


  #NAS1
  nas1: 
    build: nas/
    image: nas
    privileged: true
    command: /bin/bash -c "sleep 100000"
    expose:
      - "24007/tcp"
      - "24008/tcp"
      - "24007/udp"
      - "24008/udp"
      - "49152/tcp"
      - "49152/udp"
      - "38465-38467/tcp"
      - "38465-38467/udp"
      - "111/tcp"
      - "111/udp"
    networks:
      LAN4: 
        ipv4_address: 10.1.4.21


  #NAS2
  nas2: 
    build: nas/
    image: nas
    privileged: true
    command: /bin/bash -c "sleep 100000" 
    expose:
      - "24007/tcp"
      - "24008/tcp"
      - "24007/udp"
      - "24008/udp"
      - "49153/tcp"
      - "49153/udp"
      - "38465-38467/tcp"
      - "38465-38467/udp"
      - "111/tcp"
      - "111/udp"
    networks:
      LAN4: 
        ipv4_address: 10.1.4.22



  #NAS3
  nas3: 
    build: nas/
    image: nas
    privileged: true
    command: /bin/bash -c "sleep 100000"
    expose:
      - "24007/tcp"
      - "24008/tcp"
      - "24007/udp"
      - "24008/udp"
      - "49154/tcp"
      - "49154/udp"
      - "38465-38467/tcp"
      - "38465-38467/udp"
      - "111/tcp"
      - "111/udp"
    networks:
      LAN4: 
        ipv4_address: 10.1.4.23



networks:
  LAN2:
    driver: bridge
    ipam:
      driver: default
      config: 
        - subnet: 10.1.2.0/24
  LAN3:
    driver: bridge
    internal: true
    ipam:
      driver: default
      config: 
        - subnet: 10.1.3.0/24
  LAN4:
    driver: bridge
    internal: true
    ipam:
      driver: default
      config: 
        - subnet: 10.1.4.0/24

  